language: objective-c
osx_image: xcode8

script:
 - xcodebuild test -workspace AcknowList.xcworkspace -scheme AcknowList -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' ONLY_ACTIVE_ARCH=NO
