language: objective-c
osx_image: xcode11

script:
 - xcodebuild test -project AcknowList.xcodeproj -scheme AcknowList -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.0' ONLY_ACTIVE_ARCH=NO
