language: objective-c
osx_image: xcode9

script:
 - xcodebuild test -workspace AcknowList.xcworkspace -scheme AcknowList -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' ONLY_ACTIVE_ARCH=NO
